### ISSUE TITLE
mkSymbolicEnumeration causes infinite recursion in ghc 8.6.3

### ISSUE THREAD

**Issue by foshardware** [LeventErkok/sbv#445]
The generator for `mkSymbolicEnumeration` in Data.SBV.Client causes infinite recursion on compile with ghc 8.6.3 on Windows.

Steps to reproduce:

add a stack.yaml with content:

```yaml
packages:
- .
resolver: lts-13.4
```

then run `stack build`
