### ISSUE TITLE
Bug: "Exception: Expected a sequence constant, but received: ECon"

### ISSUE THREAD

**Issue by yaitskov** [LeventErkok/sbv#594]
Hi,

I get exception when proving unsat expression below.
if predicates are equal (i.e.  `\s -> s = 1+ 4` <=> `\s -> s = 3 + 2`) then Q.E.D.
```
cabal repl
```

```
import Data.SBV
import Data.SBV.Tools.BoundedList

prove (forAll ["l"] $ \(l :: SList Word8) -> bfilter 10 ( \(s :: SWord8) -> s .== 1 + 4) l .== bfilter 10 ( \(s :: SWord8) -> s .== 3 + 2 - 1) l ) 
*** Exception: Expected a sequence constant, but received: ECon "\"\\x04\""
CallStack (from HasCallStack):
  error, called at ./Data/SBV/Control/Utils.hs:831:64 in sbv-8.14-9f0fe828128ae311221727f37c06a75fd7e83e46da5a20ae1e6300bfb7ce2b6b:Data.SBV.Control.Utils
```

```
ghc 8.10.4
sbv version 8.14
Z3 version 4.8.10 - 64 bit
```

package.yaml
```
name: my-sbv-app
version: 0.1
build-type: Simple

ghc-options: -Wall -fwarn-unused-binds -fwarn-unused-imports -fwarn-incomplete-patterns

library:
  source-dirs: src
  exposed-modules:
    - MySbvApp
  default-extensions:
    - MultiWayIf
    - GeneralizedNewtypeDeriving
    - DeriveDataTypeable
    - DeriveGeneric
    - CPP
    - TypeApplications
    - ScopedTypeVariables
    - AllowAmbiguousTypes
  dependencies:
    - base >=4.10 && <5
    - sbv >= 8.14
    - mtl >= 2.2.2
    - containers >= 0.6.5.1
```

default.nix
```
{
  ghc ? "ghc8106",
  pkgs ? import <nixpkgs> {}
}:
with pkgs.haskell.lib;
let
  haskellPkgs = pkgs.haskell.packages.${ghc};
  inherit (pkgs) lib;

  # trace = builtins.trace;
  mySourceRegexes = [
    "^src.*$"
    "^test.*$"
    "^exec.*$"
    "^examples.*$"
    "^.*\\.cabal$"
    "package.yaml"
  ];

  fromHackage = haskellPkgs.callHackageDirect;


  myApp = (haskellPkgs.callCabal2nix "my-sbv-app"
      (lib.sourceByRegex ./. mySourceRegexes) { });

  shell = haskellPkgs.shellFor {
    packages = p: [];
    nativeBuildInputs = [ haskellPkgs.hpack myApp ];
    shellHook = ''
      set -e
      hpack
      set +e
    '';
  };
in {
  inherit shell;
}
```
